@echo off
echo Creating virtual environment...
python -m venv virtual_environment

echo Activating virtual environment...
call virtual_environment\Scripts\activate

echo Checking for required libraries...
pip install --upgrade pip

echo Installing dependencies...
pip install -r requirements.txt

echo Running Streamlit app...
streamlit run app.py
