name: Run Python Installer on GitHub Actions

on: [push, pull_request]

jobs:
  run-batch-script:
    runs-on: windows-latest  # Running on Windows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Adjust if needed

      - name: Install dependencies and run script
        shell: cmd
        run: |
          python -m pip install --upgrade pip
          python_installer.bat
