name: Run Batch File

on: 
  push:
    branches:
      - main

jobs:
  run-batch:
    runs-on: windows-latest  # Uses a Windows environment to run the .bat file

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Batch File
        run: python_installer.bat
        shell: cmd
